### PR TITLE
[1.x] fix: private discussion visibility race window, self-exclusion, and permission bugs

### LINKED ISSUE #168: User is able creating a PD without being a recipient
## Bug Report

**Current Behavior**
A user is able to create a private discussion without being a recipient when he deletes himself in the initial recipient's selection.

**Steps to Reproduce**
1. Create a new PD
2. Remove own user from recipients
3. Post discission

**Expected Behavior**
The user is prevented from creating PDs that he is not part of.

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.1.1

**Possible solution(s)**
Prevent user from removing himself/ display a warning when a user tries to delete himself that he's not able adding himself back again

**Additional Context**
Posts from discussion which user 6 created and invited users 2 and 4 while removing himself:
```
DB [flarum]> select id,user_id,type,content from posts where discussion_id = 123;
+-------+---------+--------------------+--------------------------------------------------------------------+
| id    | user_id | type               | content                                                            |
+-------+---------+--------------------+--------------------------------------------------------------------+
|  1234 |       6 | comment            | <t><p>Content</p></t>                                              |
|  1235 |       6 | recipientsModified | {"new":{"users":[2,4],"groups":[]},"old":{"users":[],"groups":[]}} |
+-------+---------+--------------------+--------------------------------------------------------------------+
```

### LINKED ISSUE #239: Private discussion exposed to all logged-in users for 1–2 seconds during creation
## Summary

When a user creates a private discussion, fof/byobu writes `is_private=0` to the database on the first save and only corrects it to `is_private=1` on a second save 1–2 seconds later. During this window the discussion appears in the public discussion list (`/all`) for every logged-in user, regardless of whether they are a recipient. Any user whose Flarum SPA polls for new discussions during this window will see the private discussion title and can click through to read the full content.

**This has been confirmed in a production incident.** A user not party to a private message was able to read its full contents — including personal data — by clicking through from the discussion list during the exposure window.

## Root Cause

The `is_private` flag is computed during Eloquent's `saving` hook by `GetModelIsPrivate`, which reads the recipient relationship from the database. At the time of the first save (in `StartDiscussionHandler::handle()`), recipients have not yet been inserted — they are queued as an `afterSave` callback by `PersistRecipients`. The flag is therefore computed as `false` on the first save. Recipients are then inserted, `CreatePostWhenRecipientsChanged` creates a `recipientsModified` system post (~1–2 seconds of processing), and only then does a second save correctly compute and write `is_private=1`.

The sequence:

1. `$discussion->save()` → `saving` event → `GetModelIsPrivate` reads empty recipients from DB → **`is_private=0` written to DB**
2. `afterSave` → recipients inserted into `recipients` table
3. `PostReply` dispatched → post #1 (message content) created
4. `dispatchEventsFor($discussion)` → `Events\Created` fires → `CreatePostWhenRecipientsChanged` creates `recipientsModified` post #2
5. `$discussion->save()` → `saving` event → `GetModelIsPrivate` now reads recipients from DB → **`is_private=1` written to DB**

Between steps 1 and 5 (measured at 1–2 seconds in production), the discussion is visible to all logged-in users via a standard `GET /api/discussions` request.

## Suggested Fix

In `PersistRecipients::handle()`, when `!->discussion->exists` and the screener has recipients, set `$event->discussion->is_private = true` directly — before the first save occurs. This ensures `is_private=1` is written on the initial INSERT, closing the window entirely.

A more robust fix would wrap the entire discussion creation flow in a database transaction so no intermediate state is ever visible to concurrent connections.

## Workaround

Remove the `discussion.startPrivateDiscussionWithUsers` and `discussion.startPrivateDiscussionWithGroups` permissions from all non-admin groups until a patch is released. Members can still reply to existing private discussions; only creation of new ones is blocked.

### PR DESCRIPTION
**Pull request by imorland**
## Summary

- **#239** — `is_private=0` race window on creation: `PersistRecipients` now sets `is_private=true` and pre-populates the relation cache before the first INSERT, preventing stale-object saves from resetting it back to `0`
- **#168** — Creator excluded from own recipients: actor is always injected into the recipient collection on creation, ensuring they can read their own discussion and unblocking `PostReplyHandler`'s scoped visibility lookup
- **Permission string mismatch** — `startPrivateDiscussionWithBlockers` was checked without the `discussion.` prefix in both `PersistRecipients` and `AllowsPdGambit`, so the override permission never functioned
- **`Arr::exists` → `Arr::has`** in `DropTagsOnPrivateDiscussions` — `Arr::exists` does not support dot-notation paths, so tags were never stripped from private discussion creation payloads

## Tests

Integration tests added covering all four fixes, run in two configurations via an abstract base class:
- `CreatePrivateDiscussionTest` — without `flarum/tags`
- `CreatePrivateDiscussionWithTagsTest` — with `flarum/tags`, plus tags-specific assertions

32 tests, all passing.

### CODE REVIEW

**Review by DavideIadeluca — APPROVED** [review]
Smoke tested this locally. Looking good from my side. Tested:
* Create new private discussion & verify it's not accessible for other users ✅
* Block private discussion permission -> working as expected ✅
* Trying to self exclude myself from the private discussion -> didn't work: my user got added automatically ✅

File: src/Listeners/PersistRecipients.php [hunk 1]
```diff
@@ -60,25 +60,46 @@ public function handle(Saving $event)
...
+        // Set is_private immediately on new discussions so the first INSERT writes
+        // is_private=1, closing the race window where the discussion is briefly
+        // visible to non-recipients (issue #239).
+        //
+        // Also pre-populate the relation cache on this $discussion object so all
+        // subsequent saves on the same stale instance (e.g. the final save in
+        // StartDiscussionHandler) also see non-empty recipients and keep is_private=1
+        // rather than resetting it to 0.
+        if (!$event->discussion->exists && $this->screener->isPrivate()) {
+            $event->discussion->is_private = true;
```
Comment (grimur82) [inline src/Listeners/PersistRecipients.php:98]: Is `$event->discussion->is_private = true` needed here? Since the relation cache is pre-populated from the payload below, `GetModelIsPrivate` should see the recipients during the model `saving` hook and let
  `ModelPrivate` set `is_private = true`. If so, this assignment seems redundant/defensive, while the `setRelation(...)` calls are the important part.

File: src/Listeners/DropTagsOnPrivateDiscussions.php [hunk 2]
```diff
@@ -29,8 +29,8 @@ public function __construct(ExtensionManager $extensions)
 
     public function handle(Saving $event)
```
Comment (grimur82) [inline src/Listeners/DropTagsOnPrivateDiscussions.php:30]: Would it be worth extracting some of these blocks in handle method into intent-named private methods? 
Some examples
```
$this->assertRecipientChangeAllowed($event);
$this->prepareNewPrivateDiscussion($event);
$this->assertRecipientLimitAllowed($event);
$this->primePrivacyStateForNewDiscussion($event);

```
